name: Jupyter Notebook Formatting

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install black==22.3.0  # Pin black to a compatible version
          pip install black-nb==0.3.0 # Compatible version
          pip install regex  # Ensure regex is available

      - name: Check for Jupyter Notebooks
        id: notebooks-check
        run: |
          if [ -z "$(find . -name '*.ipynb')" ]; then
            echo "No Jupyter notebooks found."
            exit 0
          fi

      - name: Run black-nb on notebooks
        if: steps.notebooks-check.outcome == 'success'
        run: |
          black-nb ./**/*.ipynb
